def detect_problems(filename):
	
    """
    Detect errors from a file.

    Args:
        filename :


    (Generated by docly)
    """
    data = numpy.loadtxt(fname=filename, delimiter=',')
    if numpy.max(data, axis=0)[0] == 0 and numpy.max(data, axis=0)[20] == 20:
        print('Suspicious looking maxima!')
    elif numpy.sum(numpy.min(data, axis=0)) == 0:
        print('Minima add up to zero!')
    else:
        print('Seems OK!')